name: Adds all issues and PRs to Nero's Project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues/PRs to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/NeroGM/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}