name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install dependencies
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - run: |
        haxe -version
        haxelib install heaps --always
        haxe tpl/compile_js.hxml
        echo Build end.
