name: "Build Test: Javascript"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      
      - name: Installing Heaps + Ase
        run: |
          haxelib git heaps https://github.com/HeapsIO/heaps
          haxelib git ase https://github.com/miriti/ase
      
      - name: Set the repo as development directory
        run: |
          cd ../
          haxelib dev nbase nbase
        
      - name: Create test project
        run: |
          cd ../
          haxelib run nbase test
      
      - name: 'Building: Javascript'
        run: |
          cd ../test/
          haxe basic.hxml -js "build/js/game.js" -m Main --macro MacroInit.init() --macro addGlobalMetadata('h2d.Object','@:build(nb.Macros.extH2dObject())')
        shell: cmd
