name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - run: haxe -version
      
      - run: haxelib install heaps
      
      - name: Building Javascript
        run: |
          cd tpl/
          haxe basic.hxml -js "build/js/game.js" -m Main --macro MacroInit.init() --macro addGlobalMetadata('h2d.Object','@:build(nb.Macros.extH2dObject())')
